package cli

import (
	_ "embed"
	"fmt"

	"github.com/spf13/cobra"
)

// The notices this binary is required to carry. Embedded rather than shipped
// beside the binary: Homebrew installs only the binary and Nix builds from
// source, so a release asset would reach neither, and the licences oblige
// whoever distributes the binary — which is us, on every one of those paths.
//
// Generated by scripts/third-party-licenses.ts; CI fails on a stale copy.
//
//go:embed THIRD_PARTY_LICENSES.md
var thirdPartyLicenses string

var licensesCmd = &cobra.Command{
	Use:   "licenses",
	Short: "Show the licenses of the third-party code compiled into fpcloud",
	Long: "Show the licenses of the third-party code compiled into fpcloud.\n\n" +
		"fpcloud itself is Apache-2.0. The modules it links are offered on their\n" +
		"own terms, reproduced here in full.",
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		_, err := fmt.Fprint(cmd.OutOrStdout(), thirdPartyLicenses)
		return err
	},
}

func init() {
	rootCmd.AddCommand(licensesCmd)
}
